name: formal_verification
on: [push]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Manta from Source
        run: |
          pip install setuptools --upgrade

          # omitting the following commmand causes the version of setuptools
          # used by python to get confused, and it doesn't detect the name
          # or version of the package from pyproject.toml - so the following
          # workaround is used:
          # https://github.com/pypa/setuptools/issues/3269#issuecomment-1254507377
          export DEB_PYTHON_INSTALL_LAYOUT=deb_system

          python3 -m pip install .

      - name: Install oss-cad-suite
        run: |
          wget --no-verbose https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2023-02-23/oss-cad-suite-linux-x64-20230223.tgz
          tar -xzf oss-cad-suite-linux-x64-20230223.tgz
          echo "$(pwd)/oss-cad-suite/bin" >> $GITHUB_PATH

      - name: Run formal verification
        run: make formal