name: run_tests
on: [push]
jobs:
  all:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: |
          uv python install
          uv sync --locked

      - name: Run pre-commit against all files
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: |
          source ./environment.sh
          uv run make test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage_reports
          include-hidden-files: true
          path: |
            .coverage
            coverage.xml

      - name: Show coverage report
        run: uv run coverage report

      - name: Upload results to Codecov
        run: uv run codecov -t ${{ secrets.CODECOV_TOKEN }}
